version: 2
updates:

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "build(deps): update "
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: devcontainers
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "build(deps): update "
    groups:
      devcontainers:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "build(deps): update "
    groups:
      docker:
        patterns:
          - "*"
