name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Inject secrets
      run: echo "TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}" >> .env.backend

    - name: Build Docker containers
      run: |
        docker-compose build
